#!/bin/bash

# Script for local runs of Millau<>AlephParachain bridge
#
# Need running Millau node and AlephParachain + Rococo

MILLAU_PORT="${MILLAU_PORT:-9945}"
ROCOCO_PORT="${ROCOCO_PORT:?ROCOCO_PORT variable must be set}"
ALEPH_PARACHAIN_PORT="${ALEPH_PARACHAIN_PORT:?ALEPH_PARACHAIN_PORT must be set}"

echo "Initializing Millau <> AlephParachain bridge"

./target/debug/substrate-relay init-bridge \
    millau-to-aleph-parachain \
	--source-host localhost \
	--source-port $MILLAU_PORT \
	--target-host localhost \
	--target-port $ALEPH_PARACHAIN_PORT \
	--target-signer //Alice

./target/debug/substrate-relay init-bridge \
	rococo-to-millau \
	--source-host localhost \
	--source-port $ROCOCO_PORT \
	--target-host localhost \
	--target-port $MILLAU_PORT \
	--target-signer //Sudo

echo "Starting Millau -> AlephParachain headers relay, to see logs:"
echo "tail -f relay-aleph-parachain-headers-millau.log"

./target/debug/substrate-relay relay-headers \
	millau-to-aleph-parachain \
	--source-host localhost \
	--source-port $MILLAU_PORT \
	--target-host localhost \
	--target-port $ALEPH_PARACHAIN_PORT \
	--target-signer //Bob \
	&> relay-aleph-parachain-headers-millau.log &

echo "Starting Rococo -> Millau headers relay, to see logs:"
echo "tail -f relay-headers-rococo-millau.log"

./target/debug/substrate-relay relay-headers \
	rococo-to-millau \
	--source-host localhost \
	--source-port $ROCOCO_PORT \
	--target-host localhost \
	--target-port $MILLAU_PORT \
	--target-signer //Bob \
	&> relay-headers-rococo-millau.log &

echo "Starting Rococo -> Millau parachains relay, to see logs:"
echo "tail -f relay-parachains-rococo-millau.log"

./target/debug/substrate-relay relay-parachains \
	rococo-to-millau \
	--source-host localhost \
	--source-port $ROCOCO_PORT \
	--target-host localhost \
	--target-port $MILLAU_PORT \
	--target-signer //Bob \
	&> relay-parachains-rococo-millau.log &

echo "Starting Millau -> AlephParachain messages relay, to see logs:"
echo "tail -f relay-messages-aleph-parachain-millau.log"

./target/debug/substrate-relay relay-messages \
	millau-to-aleph-parachain \
	--source-host localhost \
	--source-signer //Bob \
	--source-port $MILLAU_PORT \
	--target-host localhost \
	--target-port $ALEPH_PARACHAIN_PORT \
	--target-signer //Bob \
	&> relay-messages-aleph-parachain-millau.log &

echo "Starting AlephParachain -> Millau messages relay, to see logs:"
echo "tail -f relay-messages-millau-aleph-parachain.log"

./target/debug/substrate-relay relay-messages \
	aleph-parachain-to-millau \
	--source-host localhost \
	--source-port $ALEPH_PARACHAIN_PORT \
	--source-signer //Bob \
	--target-host localhost \
	--target-port $MILLAU_PORT \
	--target-signer //Bob \
	&> relay-messages-millau-aleph-parachain.log &

# Set up a trap to catch the SIGINT signal (generated by Ctrl+C) and kill all background processes
trap 'kill $(jobs -p)' SIGINT

# Wait for all background processes to complete
wait