name: Test Code

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test-code:
    runs-on: self-hosted
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Rust Toolchain
      uses: Cardinal-Cryptography/github-actions/install-rust-toolchain@v1

    - name: Run Linter
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings

    - name: Run Unit Test Suite
      uses: actions-rs/cargo@v1
      with:
        command: test

    - name: Run Format Checks
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all 
